version: "2.0"
services:
    rnd_humble:
        image: rnd_v2:humble
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - ./../src:/home/humble_user/src
           
    
     

        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            

        runtime: nvidia
        
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        tty: true
        network_mode: "host"
